/* Build the AML Transaction Monitoring deck.
 *
 *   cd presentation
 *   node build_deck.js            -> AML-Transaction-Monitoring.pptx
 *
 * Charts are generated by ../scripts/make_deck_figures.py into ./figures/ and
 * embedded here as base64 (no external file links, so every viewer renders them).
 * The spoken script lives in ./speaker-notes.md (read from tablet).
 */
const fs = require("fs");
const path = require("path");
const pptxgen = require("pptxgenjs");

const CORAL = "F0523C"; // Enfuce primary accent
const INK = "1A1A1A"; // near-black: titles, dark shapes, table headers
const DARK = "0F0F0F"; // darker fill for shapes on dark slides
const PALE = "F6D9D2"; // pale coral: body text on dark slides
const WHITE = "FFFFFF";
const MUTE = "6E6E6E"; // neutral grey for secondary text
const LINE = "E4E1DF"; // light warm border
const TINT = "F6F3F2"; // very light warm grey for cards
const SLATE = "8A8078"; // warm grey: storage / governance boxes in flows

const HEAD = "Arial";
const BODY = "Calibri";

const p = new pptxgen();
p.layout = "LAYOUT_WIDE"; // 13.3 x 7.5
p.theme = { headFontFace: HEAD, bodyFontFace: BODY };

const MX = 0.6;
const CW = 13.3 - MX * 2;
const TOTAL = 25;
let PAGE = 0;

/* ---------- slide factories (every slide gets a page number) ---------- */
function pageNumber(s, dark) {
  if (PAGE === 1 || PAGE === TOTAL) return; // title and closing slides have no number
  s.addText(`${PAGE} / ${TOTAL}`, {
    x: 13.3 - 1.4, y: 7.5 - 0.42, w: 1.15, h: 0.3, align: "right",
    fontFace: BODY, fontSize: 9, color: dark ? MUTE : "B3ADA9", isTextBox: true, margin: 0,
  });
}
function darkSlide() {
  PAGE += 1;
  const s = p.addSlide();
  s.background = { color: INK };
  pageNumber(s, true);
  return s;
}
function lightSlide(part, section) {
  PAGE += 1;
  const s = p.addSlide();
  s.background = { color: WHITE };
  if (part) {
    s.addShape(p.ShapeType.ellipse, { x: MX, y: 0.5, w: 0.42, h: 0.42, fill: { color: CORAL } });
    s.addText(String(part), {
      x: MX, y: 0.5, w: 0.42, h: 0.42, align: "center", valign: "middle",
      fontFace: BODY, fontSize: 13, bold: true, color: WHITE, isTextBox: true, margin: 0,
    });
    s.addText(section.toUpperCase(), {
      x: MX + 0.55, y: 0.5, w: CW - 0.55, h: 0.42, valign: "middle",
      fontFace: BODY, fontSize: 12, bold: true, color: MUTE, charSpacing: 2, isTextBox: true, margin: 0,
    });
  }
  pageNumber(s, false);
  return s;
}
function title(s, text, y = 1.05) {
  s.addText(text, {
    x: MX, y, w: CW, h: 0.9, fontFace: HEAD, fontSize: 27, bold: true, color: INK,
    isTextBox: true, margin: 0,
  });
}
function bullets(s, items, opt = {}) {
  s.addText(
    items.map((t, i) => ({
      text: t,
      options: { bullet: { code: "2022", indent: 12 }, breakLine: i < items.length - 1, paraSpaceAfter: opt.gap ?? 8 },
    })),
    {
      x: opt.x ?? MX, y: opt.y ?? 2.1, w: opt.w ?? CW, h: opt.h ?? 4.6,
      fontFace: BODY, fontSize: opt.fontSize ?? 15, color: opt.color ?? INK, valign: "top",
      isTextBox: true, margin: 0, lineSpacingMultiple: opt.ls ?? 1.05,
    }
  );
}
function card(s, x, y, w, h, fill) {
  s.addShape(p.ShapeType.roundRect, { x, y, w, h, rectRadius: 0.06, fill: { color: fill }, line: { color: LINE, width: 1 } });
}
function cardHead(s, x, y, w, t, color = INK) {
  s.addText(t, { x: x + 0.3, y: y + 0.16, w: w - 0.6, h: 0.35, fontFace: BODY, bold: true, fontSize: 13.5, color, isTextBox: true, margin: 0 });
}
function cardBody(s, x, y, w, h, t) {
  s.addText(t, { x: x + 0.3, y: y + 0.6, w: w - 0.6, h, fontFace: BODY, fontSize: 12, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.05 });
}
function stat(s, x, y, w, big, label, color = INK) {
  s.addText(big, { x, y, w, h: 0.95, align: "center", fontFace: HEAD, fontSize: 40, bold: true, color, isTextBox: true, margin: 0 });
  s.addText(label, { x, y: y + 0.95, w, h: 0.6, align: "center", fontFace: BODY, fontSize: 12, color: MUTE, isTextBox: true, margin: 0 });
}
const HROW = { bold: true, color: WHITE, fill: { color: INK } };
function note(s, t) { s.addNotes(t); }

/* ---------- chart images: embedded as base64, never linked ---------- */
function pic(s, name, o) {
  const b64 = fs.readFileSync(path.join(__dirname, "figures", name)).toString("base64");
  s.addImage({ data: "image/png;base64," + b64, x: o.x, y: o.y, w: o.w, h: o.h });
}

/* ---------- flow diagram: small boxes joined by large block arrows ---------- */
function flow(s, steps, o) {
  const y = o.y, bh = o.h ?? 0.85, aw = o.aw ?? 0.6;
  const n = steps.length;
  const bw = (CW - aw * (n - 1)) / n;
  steps.forEach((st, i) => {
    const x = MX + i * (bw + aw);
    s.addShape(p.ShapeType.roundRect, {
      x, y, w: bw, h: bh, rectRadius: 0.04,
      fill: { color: st.fill ?? INK },
      line: st.line ? { color: INK, width: 1 } : { type: "none" },
    });
    s.addText(st.t, {
      x, y, w: bw, h: bh, align: "center", valign: "middle",
      fontFace: BODY, fontSize: o.fontSize ?? 9, bold: !!st.bold,
      color: st.color ?? WHITE, isTextBox: true, margin: 0,
    });
    if (i < n - 1) {
      s.addShape(p.ShapeType.rightArrow, {
        x: x + bw + 0.04, y: y + bh / 2 - 0.19, w: aw - 0.08, h: 0.38,
        fill: { color: CORAL }, line: { type: "none" },
      });
    }
  });
}

/* ---------- group bracket + label under a run of items (slide 9) ---------- */
function groupBrace(s, x, w, y, label, color) {
  const t = 0.13;
  s.addShape(p.ShapeType.line, { x, y: y + t, w, h: 0, line: { color, width: 1.75 } });
  s.addShape(p.ShapeType.line, { x, y, w: 0, h: t, line: { color, width: 1.75 } });
  s.addShape(p.ShapeType.line, { x: x + w, y, w: 0, h: t, line: { color, width: 1.75 } });
  s.addShape(p.ShapeType.line, { x: x + w / 2, y: y + t, w: 0, h: t, line: { color, width: 1.75 } });
  s.addText(label, {
    x: x - 0.4, y: y + t + 0.16, w: w + 0.8, h: 0.5, align: "center",
    fontFace: BODY, fontSize: 11, bold: true, color, isTextBox: true, margin: 0, lineSpacingMultiple: 1.05,
  });
}

/* ============================================================ 1. Title */
{
  const s = darkSlide();
  s.addShape(p.ShapeType.ellipse, { x: 9.9, y: -1.9, w: 6, h: 6, fill: { color: DARK } });
  s.addShape(p.ShapeType.ellipse, { x: 11.6, y: 5.0, w: 3.0, h: 3.0, fill: { color: CORAL } });
  s.addText("AML Transaction Monitoring", {
    x: MX, y: 2.35, w: 9.2, h: 1.1, fontFace: HEAD, fontSize: 42, bold: true, color: WHITE, isTextBox: true, margin: 0,
  });
  s.addText("Ranking transactions by laundering risk, within investigators' daily capacity", {
    x: MX, y: 3.6, w: 9.2, h: 0.6, fontFace: BODY, fontSize: 16, color: PALE, isTextBox: true, margin: 0,
  });
  s.addText("Hafeez Ullah", {
    x: MX, y: 5.35, w: 6, h: 0.45, fontFace: HEAD, fontSize: 17, bold: true, color: WHITE, isTextBox: true, margin: 0,
  });
  s.addShape(p.ShapeType.line, { x: MX + 0.03, y: 5.92, w: 3.4, h: 0, line: { color: CORAL, width: 2 } });
  s.addText("Enfuce  ·  Machine Learning Engineer technical case", {
    x: MX, y: 6.05, w: 8, h: 0.4, fontFace: BODY, fontSize: 12.5, color: MUTE, isTextBox: true, margin: 0,
  });
  note(s, "Thanks for the time. I will walk through a transaction-monitoring solution: the model and how I evaluated it, how I would operate it, the architecture, and a delivery plan. Parts 1 and 2 are built end to end, Parts 3 and 4 are design. Throughout, the focus is production readiness and the reasoning behind each choice, which the brief asked for over model score.");
}

/* ============================================================ 2. The problem */
{
  const s = lightSlide(1, "The problem");
  title(s, "The problem, and why the framing matters");
  card(s, MX, 1.95, CW, 1.75, TINT);
  s.addText(
    "Given a stream of transactions where about 0.1% are laundering, rank them by risk well enough " +
    "that investigators, reviewing only the top slice each day, catch as much laundering as possible " +
    "for as little wasted effort as possible.",
    { x: MX + 0.35, y: 2.15, w: CW - 0.7, h: 1.4, fontFace: HEAD, fontSize: 16, italic: true, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.15 },
  );
  bullets(s, [
    "It is a ranking problem, not a yes/no classifier. The model ranks and humans decide, so I optimise ranking quality and pick the operating threshold separately. Never a fixed 0.5 cut-off.",
    "The hard constraint is investigator capacity, not model capacity. You cannot alert on everything suspicious, so the objective is recall within a fixed daily alert budget.",
    "This is the tension the brief names: detecting suspicious activity versus generating unnecessary alerts. Every choice in this deck is judged against it.",
  ], { y: 4.05, fontSize: 13 });
  note(s, "State the problem precisely, because everything follows from it. Not a classifier, a ranker. Laundering is about 1 in 1000, investigators have fixed capacity. The question: within the alerts a team can review in a day, how much laundering do we catch for how much wasted effort. And I built it production-shaped from the start, which is what makes Part 2 possible.");
}

/* ============================================================ 3. The data */
{
  const s = lightSlide(1, "The data");
  title(s, "SAML-D: synthetic transaction data over time");
  stat(s, MX, 2.2, 3.9, "9.5M", "transactions, Oct 2022 to Aug 2023");
  stat(s, MX + 4.15, 2.2, 3.9, "0.10%", "laundering, about 1 in 960", CORAL);
  stat(s, MX + 8.3, 2.2, 3.8, "11", "monthly files, ready-made batches");
  bullets(s, [
    "Prevalence is stable, with a slight upward drift (0.10% to 0.13%), which is itself a monitoring signal",
    "Labels are per-transaction. An account that launders looks normal in about 99% of its transactions, so we score transactions, not accounts",
    "Clean data. 293k sender accounts, 90% recurring, so there is enough history for behavioural features",
    "28 named laundering typologies (Structuring, Fan-Out, Cycle, and so on), used for error analysis, never as a feature",
  ], { y: 4.0 });
  note(s, "9.5M transactions, laundering is about 1 in 1000. Two design drivers: the label is per-transaction, not per-account, so I score transactions; and the data already arrives in monthly files, which is my split unit and later my batch unit in Part 2.");
}

/* ============================================================ 4. EDA */
{
  const s = lightSlide(1, "EDA");
  title(s, "EDA: look before you build");
  s.addText("Before writing a line of model code, I checked the data against the label. Every feature decision below is grounded in a number, not an assumption.", {
    x: MX, y: 1.95, w: CW, h: 0.55, fontFace: BODY, fontSize: 12.5, italic: true, color: MUTE, isTextBox: true, margin: 0,
  });
  s.addTable(
    [
      [{ text: "What I checked", options: HROW }, { text: "What I found", options: HROW }, { text: "Decision", options: HROW }],
      ["Prevalence and stability", "0.10%, drifts 0.10% to 0.13%", "ranking problem, PR-AUC, Part 2 watches it"],
      ["Missing values", "none", "no imputation step"],
      ["Do accounts recur?", "90% of senders recur", "account-history features are viable"],
      ["Cross-border and currency-mismatch", "25% vs 10%, and 34% vs 11% (laundering vs normal)", "keep both"],
      ["Large amount (over GBP 100k)", "3.2% vs 0.3%", "keep the flag"],
      ["Night and weekend flags", "no separation", "dropped"],
      ["Laundering_type by class", "value sets are disjoint", "target leakage, excluded"],
    ],
    { x: MX, y: 2.6, w: CW, colW: [3.3, 4.6, 4.2], rowH: 0.46, fontFace: BODY, fontSize: 10.5, color: INK, valign: "middle", border: { type: "solid", color: LINE, pt: 1 } }
  );
  note(s, "EDA is the look-before-you-build step. Point at two or three rows: cross-border is a 2.5x lift, night and weekend flags were dropped for no signal, Laundering_type has disjoint value sets by class so it is a post-hoc label and using it would be leakage. The message: every feature choice traces to a number on this table.");
}

/* ============================================================ 5. The pipeline */
{
  const s = lightSlide(1, "Part 1 pipeline");
  title(s, "The Part 1 pipeline, and how it answers the brief");
  flow(s, [
    { t: "load\n+ time sort" }, { t: "transaction\nfeatures" }, { t: "entity\nfeatures" },
    { t: "temporal\nsplit" }, { t: "handle\nimbalance" }, { t: "train\nLightGBM" }, { t: "evaluate\nat budget" },
  ], { y: 2.35, h: 0.85, aw: 0.55, fontSize: 9 });
  s.addText("The rest of Part 1 zooms into each step, left to right. Every step is a decision with a rejected alternative; the next slide is the decision log behind them.", {
    x: MX, y: 3.55, w: CW, h: 0.4, fontFace: BODY, fontSize: 12, italic: true, color: MUTE, isTextBox: true, margin: 0,
  });
  s.addTable(
    [
      [{ text: "The brief asked for", options: HROW }, { text: "Pipeline step that answers it", options: HROW }],
      ["Preprocessing and feature engineering", "transaction features, entity features, leakage prevention"],
      ["Handling class imbalance", "handle imbalance"],
      ["Train, validation and test split", "temporal split"],
      ["Evaluation metric and the reasoning", "evaluate at budget, then the metric-choice slide"],
      ["Detection versus unnecessary alerts", "the recall-versus-workload slide"],
    ],
    { x: MX, y: 4.1, w: CW, colW: [4.6, 7.5], rowH: 0.48, fontFace: BODY, fontSize: 11.5, color: INK, valign: "middle", border: { type: "solid", color: LINE, pt: 1 } }
  );
  note(s, "This slide is a map, not an argument. Seven steps, left to right, and everything after this is a zoom into one of them. The table maps the brief's five asks onto the steps so you can see nothing was skipped. Keep this to fifteen seconds.");
}

/* ============================================================ 6. ADRs */
{
  const s = lightSlide(1, "How I work");
  title(s, "The decisions, written down");
  s.addText("Every choice the brief cares about is a one-page Architecture Decision Record in the repo: the decision, the alternative I rejected, and the trade-off. This slide is the index; the detail is on the slides that follow.", {
    x: MX, y: 1.95, w: CW, h: 0.7, fontFace: BODY, fontSize: 12.5, italic: true, color: MUTE, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1,
  });
  s.addTable(
    [
      [{ text: "ADR", options: HROW }, { text: "Decision", options: HROW }, { text: "Alternative rejected", options: HROW }],
      ["0002", "Score in daily batches, not real time", "streaming / per-transaction scoring"],
      ["0003", "Exclude Laundering_type from features", "use it (it is a post-hoc label: leakage)"],
      ["0004", "Split train / val / test by calendar month", "random split, or account-grouped k-fold"],
      ["0005", "Handle imbalance at the threshold, weight = 1", "cost-weight by the ratio, or SMOTE"],
      ["0006", "Gated promotion: challenger, then human sign-off", "auto-promote on a metric win"],
      ["0001", "Keep an ADR log at all", "decisions live only in commit messages"],
    ],
    { x: MX, y: 2.95, w: CW, colW: [1.0, 5.6, 5.5], rowH: 0.58, fontFace: BODY, fontSize: 11.5, color: INK, valign: "middle", border: { type: "solid", color: LINE, pt: 1 } }
  );
  note(s, "Fifteen seconds on this. Every decision the brief cares about is a one-page record in the repo, with the rejected alternative and the trade-off. I'm not going to read them; the next slides walk the important ones in detail. The point of the slide is that the reasoning is written down, which is what a regulator and a model validator both ask for.");
}

/* ============================================================ 7. Preprocessing */
{
  const s = lightSlide(1, "Preprocessing");
  title(s, "Preprocessing: deliberately minimal");
  const cw3 = (CW - 0.5) / 2;
  card(s, MX, 2.15, cw3, 2.5, TINT);
  cardHead(s, MX, 2.15, cw3, "Done on load");
  cardBody(s, MX, 2.15, cw3, 1.7,
    "Explicit dtypes, which halves the memory and puts the schema intent in code. One timestamp built from Date and Time, then a global sort by time. No missing values in the raw data, so no imputation. The only NaN is an entity feature on an account's first-ever transaction, and it means “no history”, not “missing”.");
  card(s, MX + cw3 + 0.5, 2.15, cw3, 2.5, WHITE);
  cardHead(s, MX + cw3 + 0.5, 2.15, cw3, "Differs by model", MUTE);
  cardBody(s, MX + cw3 + 0.5, 2.15, cw3, 1.7,
    "LightGBM: categoricals kept as a native category dtype, no one-hot. Trees are scale-invariant, so no scaling. The one transform kept is log1p on the amount, purely for readable feature importance.\n\n" +
    "Baseline (Logistic Regression): median-impute, standardise, one-hot, because linear models require it.");
  bullets(s, [
    "No target encoding, no PCA. They add leakage surface and opacity for no measurable gain here.",
    "The result: the tree does the work. That is exactly why the linear baseline is so much weaker.",
  ], { y: 5.05, fontSize: 13 });
  note(s, "Preprocessing is minimal for the tree by design. The heavy prep, scaling and one-hot, is only for the linear baseline. The NaN in the entity features is meaningful: it means the account has no history, not that a value is missing.");
}

/* ============================================================ 8. Feature engineering */
{
  const s = lightSlide(1, "Feature engineering");
  title(s, "Feature engineering: behaviour is the signal");
  const fcw = (CW - 0.4) / 2;
  card(s, MX, 2.05, fcw, 1.9, TINT);
  cardHead(s, MX, 2.05, fcw, "Transaction-level  ·  single row, no leakage risk");
  cardBody(s, MX, 2.05, fcw, 1.3, "log-amount, amount bands, cross-border, currency-mismatch, hour, weekday");
  card(s, MX + fcw + 0.4, 2.05, fcw, 1.9, TINT);
  cardHead(s, MX + fcw + 0.4, 2.05, fcw, "Entity-level  ·  causal, per sender and receiver");
  cardBody(s, MX + fcw + 0.4, 2.05, fcw, 1.3, "prior txn count, time since last txn, trailing 1d / 7d / 30d counts, 7d sum and mean, amount vs. the account's recent norm");
  bullets(s, [
    "Corridor flags encode a laundering move: each border or currency hop breaks the trail. Cheap, a clean split point, and they keep the per-alert reason readable.",
    "Windows chosen for meaning: 1 day catches a burst, 7 days the account's rhythm, 30 days its baseline. Every one is strictly backward-looking (next slide).",
    "Excluded on purpose: account IDs (identifiers, not behaviour) and Laundering_type (a post-hoc label, so target leakage).",
  ], { y: 4.35, fontSize: 13, gap: 10 });
  note(s, "Two groups. Transaction-level features come from one row, so no leakage risk. Entity-level features describe how the account was behaving before this transaction. The corridor flags are cheap and interpretable but not load-bearing. The real signal is behavioural: a transaction many times the account's own recent norm. Windows are chosen for meaning, not tuned. And I deliberately exclude account IDs and Laundering_type.");
}

/* ============================================================ 9. Leakage prevention */
{
  const s = lightSlide(1, "Feature engineering");
  title(s, "Leakage prevention: the features cannot see the future");
  s.addShape(p.ShapeType.roundRect, { x: MX, y: 1.95, w: CW, h: 1.95, rectRadius: 0.04, fill: { color: INK } });
  s.addText(
    [
      { text: "# frame is globally time-sorted on load", options: { color: "B7B7B7", breakLine: true, paraSpaceAfter: 6 } },
      { text: 'g = df.set_index("timestamp").groupby("Sender_account")["Amount"]', options: { color: WHITE, breakLine: true, paraSpaceAfter: 6 } },
      { text: 'df["sender_cnt_7d"] = g.rolling("7D", ', options: { color: WHITE } },
      { text: 'closed="left"', options: { color: "F6C177" } },
      { text: ").count()", options: { color: WHITE, breakLine: true, paraSpaceAfter: 6 } },
      { text: '#   closed="left" keeps the window [t-7d, t), so the current transaction is excluded', options: { color: "B7B7B7" } },
    ],
    { x: MX + 0.35, y: 2.2, w: CW - 0.7, h: 1.5, fontFace: "Courier New", fontSize: 11.5, isTextBox: true, margin: 0, lineSpacingMultiple: 1.0 },
  );
  bullets(s, [
    "closed=\"left\" makes the window [t-7d, t). It stops the instant before the current transaction, so nothing at time t or after can enter it.",
    "Expanding counts use cumcount(), so only rows already seen. An account's first-ever transaction gets count 0, not 1.",
    "Locked by a test: a 3-row toy account asserts the first transaction sees count 0, an empty window, and a null time-since-last. Break causality and the test fails in CI.",
    "Why it matters: train on future information and the model looks excellent in testing, then collapses in production. It is the most common silent ML failure.",
  ], { y: 4.3, fontSize: 13, gap: 10 });
  note(s, "This is the one place I would expect a deep dive. Every history feature answers a question about what happened before this transaction, enforced three ways: a global sort on load, closed-left on the rolling window, and cumcount for expanding counts. A unit test on a toy account locks it, so a future change cannot quietly reintroduce leakage.");
}

/* ============================================================ 10. Splitting the data */
{
  const s = lightSlide(1, "Splitting the data");
  title(s, "Splitting train, validation and test, strictly by time");
  const months = ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"];
  const bx = MX, cw = CW / 11, by = 2.35, ch = 1.0;
  months.forEach((m, i) => {
    const kind = i < 8 ? INK : i === 8 ? SLATE : CORAL;
    s.addShape(p.ShapeType.rect, { x: bx + i * cw + 0.03, y: by, w: cw - 0.1, h: ch, fill: { color: kind }, line: { type: "none" } });
    s.addText(m, { x: bx + i * cw, y: by + 0.32, w: cw, h: 0.35, align: "center", fontFace: BODY, fontSize: 10.5, bold: true, color: WHITE, isTextBox: true, margin: 0 });
  });
  groupBrace(s, bx + 0.03, 8 * cw - 0.1, by + ch + 0.14, "TRAINING\n8 months  ·  Oct 2022 to May 2023", INK);
  groupBrace(s, bx + 8 * cw + 0.03, cw - 0.1, by + ch + 0.14, "VALIDATION\nJune  ·  threshold only", SLATE);
  groupBrace(s, bx + 9 * cw + 0.03, 2 * cw - 0.1, by + ch + 0.14, "TEST\nJul + Aug  ·  touched once", CORAL);
  bullets(s, [
    "No shuffling. A random split lets August behaviour inform an October prediction, which inflates the score and hides model decay.",
    "Rejected alternative: account-grouped k-fold. It removes account leakage but still mixes time periods.",
    "Entity features are computed over the full timeline before splitting, so validation and test rows carry real history, exactly as at inference. Encoders are fit on train only.",
  ], { y: 4.85, fontSize: 12.5, gap: 9 });
  note(s, "Strictly by time. A random split is leakage and it hides decay. Account-grouped k-fold, the sensible-sounding alternative, still mixes time periods. Train is the first eight months, validation is June and is used only to pick the threshold, and test is July and August and is touched exactly once.");
}

/* ============================================================ 11. Class imbalance */
{
  const s = lightSlide(1, "Class imbalance");
  title(s, "Handling class imbalance: a threshold problem");
  pic(s, "sweep.png", { x: MX, y: 2.05, w: 6.7, h: 4.5 });
  s.addText([
    { text: "chart data pulled live from MLflow:  ", options: { color: MUTE } },
    { text: 'mlflow.search_runs(experiment_names=["aml-part1"])', options: { color: INK, fontFace: "Courier New" } },
  ], { x: MX, y: 6.6, w: 7.2, h: 0.35, fontFace: BODY, fontSize: 9.5, italic: true, isTextBox: true, margin: 0 });
  bullets(s, [
    "Three options weighed: resample (SMOTE or undersample), cost-weight the loss, or leave the loss alone and move the threshold",
    "The obvious cost-weight, the roughly 1000x imbalance ratio, collapses PR-AUC below the linear baseline of 0.012. It floods the alert queue with borderline negatives.",
    "ROC-AUC barely moves (0.86 to 0.99), so it is the wrong metric to steer by",
    "SMOTE rejected: interpolating categorical and count features invents impossible rows, and it has no place in a time-ordered split",
  ], { x: 7.5, y: 2.15, w: CW - 6.9, fontSize: 12.5 });
  note(s, "The slide I most want to discuss, because the obvious answer is wrong. This chart is not hand-made: it is read straight out of MLflow with mlflow.search_runs on the aml-part1 experiment, the five runs from one command. Weighting the positive class by the imbalance ratio makes PR-AUC about eighty times worse, below the linear baseline. The model already ranks well, so all the weighting does is push borderline negatives up the queue. Notice ROC-AUC barely moves, which previews why it is the wrong metric. I ship weight one and handle the real trade-off at the threshold.");
}

/* ============================================================ 12. The model */
{
  const s = lightSlide(1, "The model");
  title(s, "The model: LightGBM, gradient-boosted trees");
  const y = 2.15, h = 3.0, aw = 0.62;
  const w1 = 3.7, w3 = 3.7, w2 = CW - w1 - w3 - 2 * aw;

  card(s, MX, y, w1, h, TINT);
  cardHead(s, MX, y, w1, "INPUT  ·  26 features / transaction");
  s.addText([
    { text: "7  transaction-level", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 5, bold: true } },
    { text: "amount, corridor flags, time", options: { breakLine: true, paraSpaceAfter: 8, fontSize: 9.5, color: MUTE } },
    { text: "14  account-behaviour", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 5, bold: true } },
    { text: "counts, velocity, amount vs. norm; sender and receiver", options: { breakLine: true, paraSpaceAfter: 8, fontSize: 9.5, color: MUTE } },
    { text: "5  categorical", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 5, bold: true } },
    { text: "payment type, currencies, bank locations", options: { fontSize: 9.5, color: MUTE } },
  ], { x: MX + 0.32, y: y + 0.62, w: w1 - 0.6, h: h - 0.8, fontFace: BODY, fontSize: 11, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.03 });

  const mx2 = MX + w1 + aw;
  s.addShape(p.ShapeType.roundRect, { x: mx2, y, w: w2, h, rectRadius: 0.06, fill: { color: INK } });
  s.addText("LightGBM", { x: mx2, y: y + 0.3, w: w2, h: 0.5, align: "center", fontFace: HEAD, bold: true, fontSize: 18, color: WHITE, isTextBox: true, margin: 0 });
  s.addText([
    { text: "~1,900 shallow trees, depth 4", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 7, color: PALE } },
    { text: "each tree corrects the last; model is their sum", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 7, color: PALE } },
    { text: "native categoricals, handles NaN", options: { bullet: { code: "2022" }, color: PALE } },
  ], { x: mx2 + 0.35, y: y + 1.0, w: w2 - 0.7, h: h - 1.2, fontFace: BODY, fontSize: 10.5, isTextBox: true, margin: 0, lineSpacingMultiple: 1.05 });

  const mx3 = mx2 + w2 + aw;
  card(s, mx3, y, w3, h, TINT);
  cardHead(s, mx3, y, w3, "OUTPUT  ·  one score / transaction");
  s.addText([
    { text: "a risk score from 0 to 1", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 10 } },
    { text: "used to rank the day's transactions", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 10 } },
    { text: "never a yes/no on one transaction by itself", options: { bullet: { code: "2022" } } },
  ], { x: mx3 + 0.32, y: y + 0.75, w: w3 - 0.6, h: h - 1.0, fontFace: BODY, fontSize: 11, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1 });

  s.addShape(p.ShapeType.rightArrow, { x: MX + w1 + 0.09, y: y + h / 2 - 0.2, w: aw - 0.18, h: 0.4, fill: { color: CORAL }, line: { type: "none" } });
  s.addShape(p.ShapeType.rightArrow, { x: mx2 + w2 + 0.09, y: y + h / 2 - 0.2, w: aw - 0.18, h: 0.4, fill: { color: CORAL }, line: { type: "none" } });

  bullets(s, [
    "Why trees: tabular data, categoricals and skewed counts handled natively, fast to retrain for the Part 2 loop, explainable per alert via SHAP",
    "Rejected: a neural net (overkill for 26 features and 7k positives, harder to govern); XGBoost (equivalent, slower on categoricals)",
    "Baseline: Logistic Regression scores PR-AUC 0.012. LightGBM's 0.68 is the non-linearity and feature interactions earning their keep.",
  ], { y: 5.4, fontSize: 11.5, gap: 6 });
  note(s, "What the model is, in one slide. Input is 26 features per transaction. The model is a few thousand tiny shallow trees, each a small correction to the last, summed. Output is one risk score, used to rank, never a standalone yes/no. Trees because the data is tabular with categoricals and skewed counts, it retrains fast, and it is explainable per alert. The logistic regression baseline at 0.012 proves the model is doing real work.");
}

/* ============================================================ 13. MLflow */
{
  const s = lightSlide(1, "MLOps");
  title(s, "Experiment tracking and the model registry: MLflow");
  s.addText("The imbalance sweep is 5 tracked runs from one command. Every run captures params, metrics, the model artifact, the git commit and the environment.", {
    x: MX, y: 1.9, w: CW, h: 0.5, fontFace: BODY, fontSize: 12, italic: true, color: MUTE, isTextBox: true, margin: 0,
  });
  s.addTable(
    [
      [{ text: "run", options: HROW }, { text: "val PR-AUC", options: HROW }, { text: "val ROC-AUC", options: HROW }, { text: "trees used", options: HROW }],
      ["logreg baseline", "0.012", "0.883", "n/a"],
      [{ text: "lightgbm  spw = 1  (shipped)", options: { bold: true } }, { text: "0.682", options: { bold: true, color: CORAL } }, "0.990", "1993"],
      ["lightgbm  spw = 5", "0.685", "0.991", "2000"],
      ["lightgbm  spw = 100", "0.585", "0.989", "2000"],
      ["lightgbm  spw = 1003  (naive)", "0.008", "0.861", "2  (loss collapses)"],
    ],
    { x: MX, y: 2.45, w: 7.6, colW: [3.2, 1.5, 1.5, 1.4], rowH: 0.38, fontFace: BODY, fontSize: 10, color: INK, valign: "middle", border: { type: "solid", color: LINE, pt: 1 } }
  );
  card(s, 8.5, 2.45, CW - 7.9, 2.4, TINT);
  cardHead(s, 8.5, 2.45, CW - 7.9, "Model registry");
  s.addText([
    { text: "aml-transaction-monitoring", options: { breakLine: true, paraSpaceAfter: 6, bold: true, color: INK } },
    { text: "v1  as  @champion", options: { breakLine: true, paraSpaceAfter: 1, color: INK } },
    { text: "in production", options: { breakLine: true, paraSpaceAfter: 6, color: MUTE, fontSize: 9.5 } },
    { text: "v2  as  @challenger", options: { breakLine: true, paraSpaceAfter: 1, color: INK } },
    { text: "from Part 2, not yet promoted", options: { color: MUTE, fontSize: 9.5 } },
  ], { x: 8.8, y: 3.0, w: CW - 8.4, h: 1.7, fontFace: BODY, fontSize: 11, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1 });
  bullets(s, [
    "ROC-AUC barely moves across the sweep (0.86 to 0.99). PR-AUC swings 80x. That is the evidence that ROC-AUC is the wrong metric.",
    "Scoring loads models:/aml-transaction-monitoring@champion, never a version number. Promotion and rollback are one alias move, not a redeploy.",
    "Training is an offline job. The notebook loads the registered model and never retrains, so experiment and analysis stay separated.",
  ], { y: 5.35, fontSize: 11.5 });
  note(s, "The job description names MLflow first, so I show it working. The table is five real runs. Point at the trees-used column: weight one learns over 1993 rounds, the naive weight collapses at two. Point at ROC-AUC barely moving while PR-AUC swings eighty times. On the right, one model is promoted; scoring asks for the champion alias, never a version, so promotion and rollback are one move. I can open the live UI in the discussion.");
}

/* ============================================================ 14. Metric choice */
{
  const s = lightSlide(1, "Evaluation metric");
  title(s, "Choosing the metric, and the result");
  bullets(s, [
    "Accuracy and F1 rejected: a fixed 0.5 threshold is meaningless when we alert on the top 1%",
    "ROC-AUC rejected as the headline: dominated by millions of easy negatives, about 0.98 even for a weak model",
    "PR-AUC (average precision): threshold-free, and it only rewards precision on the positives, which is what an alert list lives on",
    "The result: PR-AUC 0.68 on validation, 0.54 on held-out test. The two-month drop is real decay, which is what Part 2 addresses.",
  ], { w: 5.3, y: 2.2, fontSize: 12.5 });
  pic(s, "pr_curves.png", { x: 6.2, y: 1.95, w: 6.8, h: 4.75 });
  note(s, "ROC-AUC sits at 0.98 and is meaningless at a thousand-to-one. Accuracy and F1 need a 0.5 cut we never use. PR-AUC is the honest summary. On the chart, the grey curve is validation, the coral curve is held-out test, and the dot is the operating point: the validation threshold carried over to test. The gap between the curves is the two-month decay, and that is the bridge to Part 2.");
}

/* ============================================================ 15. Detection vs alerts */
{
  const s = lightSlide(1, "Detection vs. alerts");
  title(s, "Detecting suspicious activity versus unnecessary alerts");
  s.addChart(
    p.ChartType.line,
    [{ name: "recall", labels: ["29", "58", "144", "289", "405", "577"], values: [0.49, 0.59, 0.67, 0.74, 0.77, 0.80] }],
    {
      x: MX, y: 2.15, w: 6.8, h: 4.4,
      chartColors: [CORAL], lineDataSymbol: "circle", lineSize: 3, showLegend: false, showTitle: false,
      valAxisMinVal: 0, valAxisMaxVal: 1, valAxisTitle: "recall", showValAxisTitle: true, valAxisLabelColor: MUTE, valAxisLabelFontSize: 10, valGridLine: { color: LINE, size: 1 },
      catAxisTitle: "alerts per day", showCatAxisTitle: true, catAxisLabelColor: MUTE, catAxisLabelFontSize: 10, catGridLine: { style: "none" },
    }
  );
  card(s, 7.6, 2.2, CW - 7.0, 2.3, TINT);
  cardHead(s, 7.6, 2.2, CW - 7.0, "Operating point");
  s.addText("Threshold fixed on validation at the 1% budget, applied unchanged to test:  about 405 alerts/day, precision 6.4%, recall 77%  (1390 caught, 423 missed).", { x: 7.9, y: 2.68, w: 4.5, h: 1.6, fontFace: BODY, fontSize: 11, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.14 });
  bullets(s, [
    "Where you sit on this curve is a capacity and risk-appetite decision for the investigations team, not a modelling choice",
    "Cost framing: the regulator sets a minimum recall, capacity sets the budget, and model quality decides whether both can be met",
    "The realised alert rate drifted from 1.0% to 1.4% as scores rose. Fixed threshold, moving target.",
  ], { x: 7.6, y: 4.7, w: CW - 7.0, fontSize: 11 });
  note(s, "The threshold is fixed on validation and applied blind to test. That comes out to about 405 alerts a day, roughly 26 of them real, catching just over three-quarters of laundering. The curve is the recall-versus-workload trade-off at other budgets. My job is to hand the team the curve, not to pick the point. And the realised rate drifted to 1.4 percent, which is a Part 2 hook.");
}

/* ============================================================ 16. Explainability */
{
  const s = lightSlide(1, "Explainability");
  title(s, "Every alert carries its own reason");
  pic(s, "shap_alert.png", { x: MX, y: 2.05, w: 7.3, h: 4.6 });
  bullets(s, [
    "SHAP gives an additive per-transaction breakdown: a base rate plus a signed contribution from each feature that sums to the score. Coral raises risk, grey lowers it.",
    "Not optional for an AML control. Every alert an investigator opens needs a reason; every SAR needs a documented basis; model-risk validation asks for the driver of an individual decision.",
    "The example: a cash withdrawal from an account dormant for 82 days into a heavily-used one. Most features push risk up; one, the sender's zero recent activity, pulls it down. The investigator sees exactly this.",
    "Aggregated, the same method gives the honest global importance: account-behaviour features carry the model.",
    "Tree-path-dependent SHAP is exact for GBDTs and fast enough for every alert in the batch.",
  ], { x: 8.05, y: 1.95, w: CW - 7.45, fontSize: 10.5, gap: 8 });
  note(s, "This slide answers 'can you explain a single decision'. SHAP decomposes one score into a base rate plus a signed push from each feature, and they sum exactly to the score. Walk the example: a cash withdrawal, the sending account dormant for nearly three months and only nineteen transactions old, moving money to an account with a hundred and thirty prior transactions. Those push the score up. One feature, the sender's zero transactions in the last week, pushes it down, and the grey bar shows it. The investigator sees this, not just a number. Same method aggregated gives the honest global picture. It is a regulatory requirement, not a nicety.");
}

/* ============================================================ 17. Error analysis */
{
  const s = lightSlide(1, "Error analysis");
  title(s, "Where recall comes from, and honest limits");
  pic(s, "typology_recall.png", { x: MX, y: 1.95, w: 7.1, h: 4.9 });
  s.addText("Strong where behaviour is the signal (ink). Weak on graph-structure patterns (coral), because there are no graph features yet.", {
    x: 8.0, y: 2.0, w: CW - 7.4, h: 1.3, fontFace: BODY, fontSize: 12.5, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1,
  });
  bullets(s, [
    "No graph features, so weak on fan-out and bipartite. Top of the backlog.",
    "The model decays measurably over about 2 months.",
    "Synthetic, instant labels. Real SAR outcomes lag by months.",
    "A single global threshold. A per-corridor threshold would likely lift recall.",
  ], { x: 8.0, y: 3.4, w: CW - 7.4, fontSize: 11.5, gap: 9 });
  note(s, "Per-typology recall tells the investigations team what to trust. The colour split is the point: ink where the model is strong, coral where it is weak. It is strong on the behavioural typologies, structuring and smurfing and cash withdrawal, and weak on the graph-structure ones, fan-out and bipartite, because I have no graph features yet. That is the top item on the backlog. Three other honest limits are on the right.");
}

/* ============================================================ 18. Part 2 overview */
{
  const s = lightSlide(2, "ML lifecycle and MLOps");
  title(s, "Operating the model: the lifecycle loop");
  flow(s, [
    { t: "daily\nbatch", fill: SLATE }, { t: "validate", fill: INK }, { t: "features", fill: INK },
    { t: "score", fill: INK }, { t: "alerts", fill: INK },
    { t: "MONITOR", fill: CORAL, bold: true },
    { t: "retrain\n(rolling)", fill: WHITE, color: INK, line: true },
    { t: "challenger\n+ shadow", fill: WHITE, color: INK, line: true },
    { t: "approve +\npromote", fill: WHITE, color: INK, line: true },
  ], { y: 2.15, h: 0.9, aw: 0.3, fontSize: 8.5 });
  s.addText("Dark = the daily pipeline.   Coral = monitoring, the focus of the next slide.   Outlined = the governed retrain-and-promote loop.", {
    x: MX, y: 3.25, w: CW, h: 0.35, fontFace: BODY, fontSize: 10.5, italic: true, color: MUTE, isTextBox: true, margin: 0,
  });
  s.addText("Part 1 showed the model decays in two months, so it has to be operated, not just shipped. The alerts step closes the loop: each alert an investigator dismisses or escalates to a SAR becomes a label, and those labels are what later retrains and re-scores the model.", {
    x: MX, y: 3.75, w: CW, h: 0.7, fontFace: BODY, fontSize: 12, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1,
  });
  card(s, MX, 4.75, 6.0, 1.75, TINT);
  cardHead(s, MX, 4.75, 6.0, "Demonstrated  ·  built, run on Jul + Aug");
  s.addText("monitoring on every batch, a codified retraining trigger, and a rolling-window retrain with a challenger and gated promotion", { x: MX + 0.3, y: 5.28, w: 5.4, h: 1.1, fontFace: BODY, fontSize: 11.5, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.05 });
  card(s, MX + 6.3, 4.75, CW - 6.3, 1.75, WHITE);
  cardHead(s, MX + 6.3, 4.75, CW - 6.3, "Conceptual", MUTE);
  s.addText("registry mechanics, shadow deployment, delayed and biased labels with reservoir sampling, feature-store parity, governance and audit, incident response", { x: MX + 6.6, y: 5.28, w: 5.0, h: 1.1, fontFace: BODY, fontSize: 11, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.05 });
  note(s, "The model decays, the Part 1 evaluation proved it, so it has to be operated. The three box colours are three tiers: the daily pipeline, the monitoring step which is the focus, and the governed retrain-and-promote loop. The lifecycle runs on proxy signals because true labels lag months, and the feedback loop matters: investigator decisions on alerts are where tomorrow's labels come from. I built and ran the monitoring, the trigger, and challenger promotion on the July and August batches.");
}

/* ============================================================ 19. Part 2 monitoring */
{
  const s = lightSlide(2, "ML lifecycle and MLOps");
  title(s, "Monitoring every batch, and what it caught");
  pic(s, "monitoring.png", { x: MX, y: 1.95, w: 7.8, h: 4.38 });
  bullets(s, [
    "Four layers, cheapest first: data quality, input drift (PSI), prediction drift, then delayed performance once labels arrive.",
    "Real prediction drift: the alert rate crept past the 1.5% band from 1 August on a fixed threshold.",
    "Delayed performance confirms it: precision 7.4% to 5.5%, recall 80% to 72%.",
    "The final partial batch (8k vs 30k rows) was caught by the data-quality gate, so its metrics were suppressed.",
    "The input-drift alarm also surfaced a feature bug: the two unbounded prior-txn counters drift with calendar time alone (PSI to 1.4). Tagged as known drift, excluded from the alarm, backlogged. Monitoring doing its job.",
  ], { x: 8.55, y: 1.95, w: CW - 7.95, fontSize: 10.5, gap: 9 });
  note(s, "Four layers, cheapest first, each compared to a reference snapshot versioned with the model. The four panels are the real replay output. Top-left, the alert rate climbs out of the band in August. Two findings: real prediction drift, the alert-rate breach; and a feature bug, the unbounded counters whose drift is pure calendar time. The second is exactly what you deploy monitoring to catch.");
}

/* ============================================================ 20. Part 2 retrain + promote */
{
  const s = lightSlide(2, "ML lifecycle and MLOps");
  title(s, "Trigger, retrain, challenger, gated promotion");
  bullets(s, [
    "The trigger fired on 3 August. Reasons: the scheduled monthly floor, and alert-rate drift for 3 consecutive days.",
    "Retrained on a rolling 8-month window (December 2022 to July 2023), to track current behaviour rather than all history",
    "The new model is a challenger, judged on the most recent labelled slice (August), and never promoted automatically",
  ], { w: 7.0, y: 2.15, fontSize: 13 });
  pic(s, "champ_chall.png", { x: 8.05, y: 2.15, w: 4.5, h: 3.21 });
  card(s, MX, 5.45, CW, 1.75, TINT);
  cardHead(s, MX, 5.45, CW, "Promotion is a registry operation, not a deploy");
  s.addText("The challenger beats the champion, so it is registered and the @challenger alias is set. It then awaits model-owner and compliance sign-off before it takes @champion. Scoring only ever asks for @champion, so promotion and rollback are one alias move, and the previous version stays loadable.", {
    x: MX + 0.3, y: 5.98, w: CW - 0.6, h: 1.1, fontFace: BODY, fontSize: 11.5, color: INK, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1,
  });
  note(s, "The trigger fired on 3 August for two reasons: the scheduled monthly floor and three days of alert-rate drift. I retrained on a rolling eight-month window, not all history, so the model tracks current behaviour. The chart: grey is the stale champion, coral the retrained challenger, judged on August. It clearly wins, PR-AUC 0.69 against 0.45. But it is not promoted automatically. A model owner and compliance sign off, then the alias moves. Rollback is the same move in reverse.");
}

/* ============================================================ 21. Part 3 architecture */
{
  const s = lightSlide(3, "Production architecture");
  title(s, "A daily batch pipeline on AWS");
  flow(s, [
    { t: "S3 raw\nimmutable", fill: SLATE },
    { t: "Validate\nGE / Deequ", fill: INK },
    { t: "Features\nGlue / EMR", fill: INK },
    { t: "Score\nSageMaker", fill: CORAL, bold: true },
    { t: "Rank + alert\nDynamoDB / SQS", fill: INK },
    { t: "Monitor\nEvidently", fill: SLATE },
  ], { y: 2.4, h: 0.95, aw: 0.6, fontSize: 9 });
  s.addText("Orchestration: Step Functions daily, plus a second state machine for retrain, shadow and promote.    MLflow registry on Fargate.    Terraform.", {
    x: MX, y: 3.7, w: CW, h: 0.4, fontFace: BODY, fontSize: 11, color: MUTE, isTextBox: true, margin: 0,
  });
  bullets(s, [
    "Batch, not streaming. The label and the workflow are both post-event, so there is no real-time decision. Add streaming only for a specific high-risk corridor if the business needs faster interdiction.",
    "The MLflow registry is the single control point. Scoring loads the champion alias, never a path. Rollback is an alias move, then re-score.",
    "The raw zone is immutable and date-partitioned, so any past batch can be re-scored with any model version.",
  ], { y: 4.35, fontSize: 12.5 });
  note(s, "Talk to the flow left to right. Raw is immutable storage. Validation sits upstream of scoring because a broken feed is the number one cause of what looks like model failure. Scoring is the one coral box, the model step. The registry is the single control point, and immutable raw plus versioned models is reproducibility: any past batch, any model version.");
}

/* ============================================================ 22. Part 3 trade-offs */
{
  const s = lightSlide(3, "Production architecture");
  title(s, "Technology choices: the trade-offs");
  s.addTable(
    [
      [{ text: "Decision", options: HROW }, { text: "Choice", options: HROW }, { text: "Alternative", options: HROW }, { text: "Why this way", options: HROW }],
      ["Serving", "Daily batch", "Streaming", "Post-event problem, so batch is simpler with no train/serve skew"],
      ["Compute", "SageMaker", "EKS with Kubeflow", "Managed, minimal ops for a small team"],
      ["Registry", "MLflow, self-hosted", "SageMaker Model Registry", "One tool for tracking and registry, portable, team standard"],
      ["Feature compute", "Glue / EMR Serverless", "Pandas on a big box", "Scales past 10x volume, serverless"],
      ["Feature storage", "S3 table plus shared code", "SageMaker Feature Store", "Batch-only, so parity without the infrastructure"],
      ["Case management", "Buy", "Build a UI", "Not the differentiation, and it fits the investigator workflow"],
    ],
    { x: MX, y: 2.15, w: CW, colW: [2.2, 2.7, 2.7, 4.5], rowH: 0.6, fontFace: BODY, fontSize: 10.5, color: INK, valign: "middle", border: { type: "solid", color: LINE, pt: 1 } }
  );
  note(s, "Every choice is biased toward less operational burden for a small team. For each row I can name the alternative and the condition under which I would switch: EKS if the organisation already runs Kubernetes, a feature store if a real-time path appears, build the case-management UI only if an off-the-shelf one does not fit the investigator workflow.");
}

/* ============================================================ 23. Part 4 delivery */
{
  const s = lightSlide(4, "Delivery");
  title(s, "From proof of concept to production over 3, 6 and 9 months");
  s.addText("Principle: reliability, then automation, then sophistication. It is a regulated control, so the risks are operational, not modelling. The model never hard-replaces the rules engine: shadow, then parallel, then staged retirement.", {
    x: MX, y: 1.95, w: CW, h: 0.7, fontFace: BODY, fontSize: 12, italic: true, color: MUTE, isTextBox: true, margin: 0,
  });
  const cols = [
    ["0 to 3 months: make it trustworthy", ["Reliable pipeline and data validation", "One model, fully monitored", "Shadow mode, action nothing", "Baselines agreed with compliance"], "You cannot operate, or get sign-off for, a control you cannot see."],
    ["3 to 6 months: make it self-sustaining", ["Automated retraining with challengers", "Investigator feedback loop for labels", "Reservoir sampling for unbiased recall", "Run in parallel with rules"], "Label lag is months, so the feedback loop must start early."],
    ["6 to 9 months: make it better and auditable", ["Graph features and typology models", "Per-corridor thresholds", "Full model cards, annual validation", "Staged rules retirement"], "The lowest-risk work, and only after the foundations hold."],
  ];
  const cw2 = (CW - 0.6) / 3;
  cols.forEach(([hd, items, why], i) => {
    const x = MX + i * (cw2 + 0.3);
    card(s, x, 2.8, cw2, 3.7, i === 0 ? TINT : WHITE);
    s.addText(hd, { x: x + 0.25, y: 3.0, w: cw2 - 0.5, h: 0.7, fontFace: BODY, bold: true, fontSize: 12, color: INK, isTextBox: true, margin: 0 });
    s.addText(items.map((t) => ({ text: t, options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 6 } })).concat([{ text: why, options: { italic: true, color: MUTE, paraSpaceBefore: 6 } }]), {
      x: x + 0.25, y: 3.5, w: cw2 - 0.5, h: 3.0, fontFace: BODY, fontSize: 10.5, color: INK, isTextBox: true, margin: 0,
    });
  });
  note(s, "Reliability first, sophistication last, which is the opposite of the instinct. Shadow before parallel before retirement. Each stage has an exit criterion: the pipeline SLA met for four weeks, then two clean automated retrains, and so on. The feedback loop starts in phase two because label lag is months and it has to be running before the labels are needed.");
}

/* ============================================================ 24. Summary */
{
  const s = darkSlide();
  s.addShape(p.ShapeType.ellipse, { x: -2, y: 4.4, w: 5.5, h: 5.5, fill: { color: DARK } });
  s.addText("What I would want you to take away", { x: MX, y: 0.8, w: CW, h: 0.8, fontFace: HEAD, fontSize: 28, bold: true, color: WHITE, isTextBox: true, margin: 0 });
  s.addText([
    { text: "Framed as alerting, not classification: recall at a fixed workload", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 10, color: PALE } },
    { text: "Causal features, a temporal split, and imbalance treated as a threshold problem. Each choice was tested against an alternative, not asserted.", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 10, color: PALE } },
    { text: "Every alert is explained with SHAP, which a regulated control needs", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 10, color: PALE } },
    { text: "The model decays measurably in 2 months, and Part 2 makes that operable", options: { bullet: { code: "2022" }, breakLine: true, paraSpaceAfter: 10, color: PALE } },
    { text: "The production seams are already in place: package, ADRs, MLflow, registry", options: { bullet: { code: "2022" }, color: PALE } },
  ], { x: MX, y: 1.8, w: 8.3, h: 3.8, fontFace: BODY, fontSize: 14.5, isTextBox: true, margin: 0, lineSpacingMultiple: 1.1 });
  s.addText("77%", { x: 8.9, y: 5.0, w: 3.8, h: 1.1, align: "center", fontFace: HEAD, fontSize: 54, bold: true, color: CORAL, isTextBox: true, margin: 0 });
  s.addText("of laundering caught\nat about 400 alerts per day", { x: 8.9, y: 6.1, w: 3.8, h: 0.8, align: "center", fontFace: BODY, fontSize: 12, color: PALE, isTextBox: true, margin: 0 });
  s.addText("recall at the 1% validation budget, applied to held-out test (1390 of 1813)", { x: 8.4, y: 6.88, w: 4.9, h: 0.35, align: "center", fontFace: BODY, fontSize: 8.5, color: "9A9A9A", isTextBox: true, margin: 0 });
  note(s, "To close: I treated it as alerting, not classification, and made every choice with investigator workload in mind, testing each against an alternative rather than asserting it. Every alert is explained. The headline is 77 percent of laundering caught at about 400 alerts a day, and it decays in two months, which is exactly what Part 2 is built for.");
}

/* ============================================================ 25. Thank you */
{
  const s = darkSlide();
  s.addShape(p.ShapeType.ellipse, { x: 9.9, y: -1.9, w: 6, h: 6, fill: { color: DARK } });
  s.addShape(p.ShapeType.ellipse, { x: 11.6, y: 5.0, w: 3.0, h: 3.0, fill: { color: CORAL } });
  s.addText("Thank you", {
    x: MX, y: 2.55, w: 9.2, h: 1.15, fontFace: HEAD, fontSize: 46, bold: true, color: WHITE, isTextBox: true, margin: 0,
  });
  s.addText("Questions and discussion", {
    x: MX, y: 3.9, w: 9.2, h: 0.6, fontFace: BODY, fontSize: 17, color: PALE, isTextBox: true, margin: 0,
  });
  s.addText("Hafeez Ullah", {
    x: MX, y: 5.45, w: 6, h: 0.45, fontFace: HEAD, fontSize: 15, bold: true, color: WHITE, isTextBox: true, margin: 0,
  });
  s.addShape(p.ShapeType.line, { x: MX + 0.03, y: 6.0, w: 3.0, h: 0, line: { color: CORAL, width: 2 } });
  s.addText("AML Transaction Monitoring  ·  Enfuce technical case", {
    x: MX, y: 6.12, w: 8, h: 0.4, fontFace: BODY, fontSize: 12, color: MUTE, isTextBox: true, margin: 0,
  });
  note(s, "Thank you. Happy to go as deep as you like on any part of it: the imbalance sweep, the leakage handling, the monitoring, the architecture trade-offs, or the delivery plan.");
}

p.writeFile({ fileName: "AML-Transaction-Monitoring.pptx" }).then((f) => console.log("wrote", f));
